// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibWebApi.Models;

public partial class Book
{
    public long BookId { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public string Isbn { get; set; }

    public DateTime? PublishedYear { get; set; }

    public int? AvailableCopies { get; set; }
}