// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibWebApi.Models;

public partial class BorrowRecord
{
    public long BorrowId { get; set; }

    public long? MemberId { get; set; }

    public long? BookId { get; set; }

    public DateTime? BorrowDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public bool? IsReturned { get; set; }
}