// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LibWebApi.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LibWebApi.Models
{
    public partial interface ILibDBContextProcedures
    {
        Task<int> usp_AddBookAsync(string title, string author, string iSBN, DateTime? publishedYear, int? availableCopies, OutputParameter<string> errorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_AddMemberAsync(string name, string email, string phone, DateTime? dateJoined, OutputParameter<string> errorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_BookIssuedAsync(long? memberId, long? bookId, OutputParameter<string> errorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetAllBooksResult>> usp_GetAllBooksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetAllBorrowedBooks_ByMemberIdResult>> usp_GetAllBorrowedBooks_ByMemberIdAsync(long? memberId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetOverdueBooksResult>> usp_GetOverdueBooksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetRecentFrequentBorrowersResult>> usp_GetRecentFrequentBorrowersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetTop5MostBorrowedBooksResult>> usp_GetTop5MostBorrowedBooksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_ReturnBookAsync(long? borrowId, long? bookId, OutputParameter<string> errorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
