// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibWebApi.Models
{
    public partial class usp_GetOverdueBooksResult
    {
        public long BookId { get; set; }
        public long MemberId { get; set; }
        public long BorrowId { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(50)]
        public string BorrowedBy { get; set; }
        [StringLength(15)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        public DateTime? BorrowedOn { get; set; }
        [StringLength(12)]
        public string Status { get; set; }
        [StringLength(35)]
        public string OverDue { get; set; }
    }
}
