// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibWebApi.Models
{
    public partial class usp_GetAllBooksResult
    {
        public long BookId { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(50)]
        public string Author { get; set; }
        [StringLength(13)]
        public string ISBN { get; set; }
        public DateTime? PublishedYear { get; set; }
        public int? AvailableCopies { get; set; }
        [StringLength(11)]
        public string AvailabilityStatus { get; set; }
    }
}
