// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibWebApi.Models
{
    public partial class usp_GetTop5MostBorrowedBooksResult
    {
        public long BookId { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public int? BorrowCount { get; set; }
    }
}
