// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibWebApi.Models
{
    public partial class usp_GetRecentFrequentBorrowersResult
    {
        public long MemberId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? BorrowedBookCount { get; set; }
    }
}
